name: pack_bags
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flashy_tab_bar2: ^0.0.5
  flutter_native_splash: ^2.3.5
  iconsax: ^0.0.8
  image_picker: ^1.2.0
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  carousel_slider: ^5.1.1
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  fluttertoast: ^9.0.0
#  hubble_razorpay_flutter: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/ad banner/
    - assets/icon/
    - assets/animation/
    - assets/onbodyimage/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/shopping-online.png"

#flutter_native_splash:
#  color: "#000000"
#  image: "assets/animation/shopping-cart.gif"
#  android: true
#  ios: true


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package